<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= esc($title ?? 'Material QR Codes - Print') ?></title>
    
    <!-- Bootstrap 5 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    
    <style>
        @media print {
            .no-print {
                display: none !important;
            }
            .qr-label-card {
                page-break-inside: avoid;
                break-inside: avoid;
            }
        }
        
        body {
            background: white;
            padding: 20px;
        }
        
        .qr-label-card {
            border: 2px solid #000;
            padding: 15px;
            margin-bottom: 20px;
            text-align: center;
            min-height: 200px;
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            background: white;
        }
        
        .qr-code-container {
            margin: 10px 0;
        }
        
        .qr-code-container img {
            max-width: 150px;
            height: auto;
            border: 1px solid #ddd;
        }
        
        .material-info {
            font-size: 12px;
            margin-top: 10px;
        }
        
        .material-name {
            font-weight: bold;
            font-size: 14px;
            margin-bottom: 5px;
        }
        
        .material-code {
            font-family: monospace;
            font-size: 11px;
            color: #666;
        }
        
        .print-header {
            margin-bottom: 30px;
            padding-bottom: 15px;
            border-bottom: 2px solid #000;
        }
        
        .print-header h1 {
            font-size: 24px;
            margin: 0;
        }
        
        .print-header p {
            margin: 5px 0;
            font-size: 12px;
        }
    </style>
</head>
<body>
    <!-- Print Controls (Hidden when printing) -->
    <div class="no-print mb-4">
        <div class="d-flex justify-content-between align-items-center">
            <div>
                <h2><i class="bi bi-qr-code"></i> Material QR Codes - Print View</h2>
                <p class="text-muted">Generate and print QR codes for all materials</p>
            </div>
            <div>
                <button onclick="window.print()" class="btn btn-primary me-2">
                    <i class="bi bi-printer"></i> Print
                </button>
                <a href="<?= base_url('warehouse-manager/materials') ?>" class="btn btn-secondary">
                    <i class="bi bi-arrow-left"></i> Back to Materials
                </a>
            </div>
        </div>
        
        <div class="alert alert-info mt-3">
            <i class="bi bi-info-circle"></i> 
            <strong>Instructions:</strong> Click "Print" to print all QR codes. Each QR code label can be cut and pasted onto the physical material.
        </div>
    </div>

    <!-- Print Header (Shown when printing) -->
    <div class="print-header">
        <h1>Material QR Codes - WITMS</h1>
        <p>Generated on: <?= date('F d, Y h:i A') ?></p>
        <p>Generated by: <?= esc($user['full_name'] ?? 'Warehouse Manager') ?></p>
    </div>

    <!-- QR Code Labels Grid -->
    <div class="container-fluid">
        <div class="row">
            <?php if (!empty($materials)): ?>
                <?php foreach ($materials as $material): ?>
                    <div class="col-md-4 col-sm-6 mb-4">
                        <div class="qr-label-card">
                            <!-- QR Code -->
                            <div class="qr-code-container">
                                <?php if (!empty($material['qr_code_url'])): ?>
                                    <img src="<?= esc($material['qr_code_url']) ?>" 
                                         alt="QR Code for <?= esc($material['name']) ?>"
                                         class="img-fluid">
                                <?php else: ?>
                                    <div class="text-muted">
                                        <i class="bi bi-qr-code" style="font-size: 80px;"></i>
                                        <p class="mt-2">QR Code not generated</p>
                                        <small>Generate QR code from materials list</small>
                                    </div>
                                <?php endif; ?>
                            </div>
                            
                            <!-- Material Information -->
                            <div class="material-info">
                                <div class="material-name">
                                    <?= esc($material['name']) ?>
                                </div>
                                <div class="material-code">
                                    Code: <?= esc($material['code']) ?>
                                </div>
                                <?php if (!empty($material['category_name'])): ?>
                                    <div style="font-size: 10px; color: #999; margin-top: 3px;">
                                        <?= esc($material['category_name']) ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            <?php else: ?>
                <div class="col-12">
                    <div class="alert alert-warning text-center">
                        <i class="bi bi-exclamation-triangle"></i> No materials found. Please add materials first.
                    </div>
                </div>
            <?php endif; ?>
        </div>
    </div>

    <!-- Print Footer -->
    <div class="text-center mt-4" style="font-size: 10px; color: #999;">
        <p>WITMS - Warehouse Inventory and Tracking Management System</p>
        <p>Page generated on <?= date('Y-m-d H:i:s') ?></p>
    </div>

    <!-- Bootstrap 5 JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

